from enum import StrEnum


class RightsStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    RESEARCHING = "RESEARCHING"
    PUBLIC_DOMAIN_VERIFIED = "PUBLIC_DOMAIN_VERIFIED"
    LICENSE_VERIFIED = "LICENSE_VERIFIED"
    CC0_VERIFIED = "CC0_VERIFIED"
    CC_BY_VERIFIED = "CC_BY_VERIFIED"
    CC_BY_SA_VERIFIED = "CC_BY_SA_VERIFIED"
    PERMISSION_VERIFIED = "PERMISSION_VERIFIED"
    NEEDS_LEGAL_REVIEW = "NEEDS_LEGAL_REVIEW"
    RESTRICTED = "RESTRICTED"
    REMOVED = "REMOVED"


APPROVED_RIGHTS_STATUSES = {
    RightsStatus.PUBLIC_DOMAIN_VERIFIED,
    RightsStatus.LICENSE_VERIFIED,
    RightsStatus.CC0_VERIFIED,
    RightsStatus.CC_BY_VERIFIED,
    RightsStatus.CC_BY_SA_VERIFIED,
    RightsStatus.PERMISSION_VERIFIED,
}


class CompletenessStatus(StrEnum):
    COMPLETE = "COMPLETE"
    POSSIBLY_INCOMPLETE = "POSSIBLY_INCOMPLETE"
    INCOMPLETE = "INCOMPLETE"
    UNKNOWN = "UNKNOWN"


class ImportStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    METADATA_FETCHED = "METADATA_FETCHED"
    RIGHTS_CHECK = "RIGHTS_CHECK"
    RIGHTS_APPROVED = "RIGHTS_APPROVED"
    DOWNLOADED = "DOWNLOADED"
    PARSED = "PARSED"
    CHAPTERS_EXTRACTED = "CHAPTERS_EXTRACTED"
    QUALITY_CHECK = "QUALITY_CHECK"
    READY_FOR_COVER = "READY_FOR_COVER"
    READY_TO_PUBLISH = "READY_TO_PUBLISH"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"


class MonetizationStatus(StrEnum):
    NOT_REVIEWED = "NOT_REVIEWED"
    ELIGIBLE = "ELIGIBLE"
    LOW_VALUE = "LOW_VALUE"
    RIGHTS_UNCERTAIN = "RIGHTS_UNCERTAIN"
    CONTENT_UNSAFE = "CONTENT_UNSAFE"
    DISABLED = "DISABLED"


class TakedownStatus(StrEnum):
    RECEIVED = "RECEIVED"
    REVIEWING = "REVIEWING"
    TEMPORARILY_DISABLED = "TEMPORARILY_DISABLED"
    RESOLVED = "RESOLVED"
    RESTORED = "RESTORED"
    REMOVED = "REMOVED"


class IllustrationMode(StrEnum):
    NONE = "NONE"
    IMPORTANT_CHAPTERS = "IMPORTANT_CHAPTERS"
    EVERY_5_CHAPTERS = "EVERY_5_CHAPTERS"
    EVERY_10_CHAPTERS = "EVERY_10_CHAPTERS"
    AI_SELECTED = "AI_SELECTED"
    ALL_CHAPTERS = "ALL_CHAPTERS"
